export const DataSearchHeader = [
  {
    id: 1,
    patientFullName: 'Петр Петров',
    phoneNumber: '+(996) 13-45-67',
    email: 'petr@example.com',
    position: 'Кардиолог',
    doctorFullName: 'Иван Иванов',
    dateAndTime: '2024-07-01 09:00',
    status: 'CANCELLED',
  },
  {
    id: 2,
    patientFullName: 'Анна Сидорова',
    phoneNumber: '+(996) 234-56-78',
    email: 'anna@example.com',
    position: 'Дерматолог',
    doctorFullName: 'Петр Петров',
    dateAndTime: '2024-07-02 10:30',
    status: 'CONFIRMED',
  },
  {
    id: 3,
    patientFullName: 'Дмитрий Козлов',
    phoneNumber: '+(996) 35-67-89',
    email: 'dmitry@example.com',
    position: 'Невролог',
    doctorFullName: 'Анна Сидорова',
    dateAndTime: '2024-07-03 12:00',
    status: 'COMPLETED',
  },
  {
    id: 4,
    patientFullName: 'Елена Николаева',
    phoneNumber: '+(996) 56-78-90',
    email: 'elena@example.com',
    position: 'Ортопед',
    doctorFullName: 'Дмитрий Козлов',
    dateAndTime: '2024-07-04 14:30',
    status: 'CONFIRMED',
  },
  {
    id: 5,
    patientFullName: 'Ольга Михайлова',
    phoneNumber: '+(996) 67-89-01',
    email: 'olga@example.com',
    position: 'Педиатр',
    doctorFullName: 'Елена Николаева',
    dateAndTime: '2024-07-05 16:00',
    status: 'COMPLETED',
  },
  {
    id: 6,
    patientFullName: 'Игорь Васильев',
    phoneNumber: '+(996) 78-90-12',
    email: 'igor@example.com',
    position: 'Психиатр',
    doctorFullName: 'Ольга Михайлова',
    dateAndTime: '2024-07-06 09:30',
    status: 'CONFIRMED',
  },
  {
    id: 7,
    patientFullName: 'Мария Павлова',
    phoneNumber: '+(996) 89-01-23',
    email: 'maria@example.com',
    position: 'Уролог',
    doctorFullName: 'Игорь Васильев',
    dateAndTime: '2024-07-07 11:00',
    status: 'COMPLETED',
  },
  {
    id: 8,
    patientFullName: 'Станислав Кузнецов',
    phoneNumber: '+(996) 90-12-34',
    email: 'stanislav@example.com',
    position: 'Гинеколог',
    doctorFullName: 'Мария Павлова',
    dateAndTime: '2024-07-08 13:30',
    status: 'CONFIRMED',
  },
  {
    id: 9,
    patientFullName: 'Антон Смирнов',
    phoneNumber: '+(996) 91-23-45',
    email: 'anton@example.com',
    position: 'Гастроэнтеролог',
    doctorFullName: 'Станислав Кузнецов',
    dateAndTime: '2024-07-09 15:00',
    status: 'COMPLETED',
  },
  {
    id: 10,
    patientFullName: 'Сергей Иванов',
    phoneNumber: '+(996) 12-34-56',
    email: 'sergey@example.com',
    position: 'Онколог',
    doctorFullName: 'Антон Смирнов',
    dateAndTime: '2024-07-10 16:30',
    status: 'CANCELLED',
  },
];
